server:
  port: 9870
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: 'tim-table-scheduling'

  jpa:
    properties:
      hibnernate:
        jdbc:
          batch_size: 5000

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sql_tkb
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
