server:
  port: 9870
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: 'time-table-scheduling'

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibnernate:
        jdbc:
          batch_size: 5000
    show-sql: true

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: high_school_time_table
    password: admin
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
